version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      # - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development

  database:
    image: postgres:14.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/opt/homebrew/var/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  node_modules:
  # gem_cache:
