default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bakingmanager_development

test:
  <<: *default
  database: bakingmanager_test

production:
  <<: *default
  database: bakingmanager_production
  username: bakingmanager
  password: <%= ENV['BAKINGMANAGER_DATABASE_PASSWORD'] %>
